### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by alainbeweb** [alainbeweb/Admin_carte_restau#1]
- [ ] create files database.php
- [ ] -search a doc
- [ ] -copy paste exemple code of doc
- [ ] modify the code
- [ ] testing
- [ ] compar off phpMyAdmin

**Comment by alainbeweb** [comment]
php Data Object
-create files database.php
-search a doc
-copy paste exemple code of doc
-modify the code 
-testing
-compar of phpMyAdmin
